version: '3.3'
services:
  database:
    image: postgres
    container_name: contacts_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5432:5432"